name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - next
    tags:
      - v*

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check

  build-linux:
    needs: checks
    strategy:
      matrix:
        platform:
          - name: x86_64
            runs-on: ubuntu-latest
          - name: aarch64
            runs-on: [self-hosted, linux, ARM64]
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build .#gfh

      - name: Upload ${{ matrix.platform.name }}
        uses: actions/upload-artifact@v4
        with:
          name: gfh-linux-${{ matrix.platform.name }}
          path: ./result/bin/gfh

  build-macos:
    needs: checks
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build .#gfh

      - uses: actions/upload-artifact@v4
        with:
          name: gfh-macos-${{ matrix.target }}
          path: ./result/bin/gfh

  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-linux
      - build-macos
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4

      - name: Package artifacts
        run: |
          mkdir out
          for dir in gfh-*; do
            filename="$dir.tar.gz"
            tar czf "out/$filename" -C "$dir" .
            sha256sum "out/$filename" >> "out/checksums.txt"
          done

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: ./out/*
